//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KafeOtomasyonu.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yiyecek
    {
        public int YiyecekID { get; set; }
        public string YiyecekKategori { get; set; }
        public string Yiyecekİsim { get; set; }
        public int Yiyecek_Fiyat { get; set; }
    }
}
