//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeOtomasyonu.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Icecek
    {
        public byte IcecekID { get; set; }
        public string IcecekKategori { get; set; }
        public string IcecekAd { get; set; }
        public int IcecekFiyat { get; set; }
    }
}
